name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      - name: Test with dotnet
        run: dotnet test --configuration Release

      - name: Publish with dotnet
        run: dotnet publish src/Continuous.Web/Continuous.Web.csproj --configuration Release -o artifacts

      - uses: actions/upload-artifact@v4
        with:
          name: continuous-artifact
          path: artifacts/
  
  deploy_dev:
    name: Deploy Dev
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: continuous-artifact
          path: artifacts/

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: "Deploy to Azure App Service"
        uses: azure/webapps-deploy@v2
        with:
          app-name: "app-vslzl-continuous-dev"
          package: artifacts/