name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      - name: Test with dotnet
        run: dotnet test --configuration Release
      
      - name: Publish with dotnet
        run: dotnet publish src/Continuous.Web/Continuous.Web.csproj --configuration Release -o artifacts
