name: CI

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      - name: Test with dotnet
        run: dotnet test --configuration Release

      - name: Publish with dotnet
        run: dotnet publish src/Continuous.Web/Continuous.Web.csproj --configuration Release -o artifacts

      - uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: artifacts/
  
  deploy_dev:
    name: Deploy Dev
    needs: build
    uses: ./.github/workflows/step-deploy-azure-web-apps.yml
    with:
      env: dev
      resource_group_name: rg-vslzl-continuous-dev
      app_service_name: app-vslzl-continuous-dev
    secrets: inherit
  
  deploy_prod:
    name: Deploy Prod
    needs: deploy_dev
    uses: ./.github/workflows/step-deploy-azure-web-apps.yml
    with:
      env: dev
      resource_group_name: rg-vslzl-continuous-prod
      app_service_name: app-vslzl-continuous-prod
    secrets: inherit
  